// Vragen voor het spel "Wie o Wie"
// Elke vraag gaat over wie uit de groep iets zou doen.
// De spelers kiezen een naam uit de spelerslijst als antwoord.

const QUESTIONS_WIE = [
  "Wie uit de groep zou als eerste een biertje pakken op een saaie vergadering?",
  "Wie zou het langst overleven in een zombie-apocalyps?",
  "Wie zou als eerste in paniek raken bij een stroomstoring?",
  "Wie zou als eerste toegeven bij een weddenschap om iets raars te eten?",
  "Wie zou stiekem de laatste koek opeten en doen alsof hij er nooit was?",
  "Wie zou het meest betalen voor een VIP-ticket naar een feestje?",
  "Wie is het snelst lam?",
  "Wie zou later arm worden?",
  "Wie jankt het meest over van alles en nog wat?",
  "Wie zou zijn eigen moeder verleiden om te voorkomen dat hij nooit meer alcohol drinkt?",
  "Wie is het meest racistisch?",
  "Wie zou het eerste iemands zus in AI naakt namaken?",
  "Wie heeft zijn piek op de middelbare school gehad?",
  "Wie joint het snelst de NSB?",
  "Wie zou het eerste een vriend of vriendin Only Fans model laten worden?",
  "Wie zit er het meest onder de duim?",
  "Wie is de grootste meeloper?",
  "Wie kan er nou echt net niks?",
  "Wie date boven zijn/haar niveau?",
  "Wiens baan zou je echt niet willen?",
  "Met wie zou je niet van leven willen ruilen?",
  "Wie is de slechtste drinker van de groep?",
  "Wie heeft nu de slechtste outfit aan?",
  "Wie zou de beste comedian zijn?",
  "Wie is het meest kinky?",
  "Wie laat zich het meest domineren door zijn vriend/vriendin?",
  "Wie gaat het eerst vreemd?",
  "Wie stuurt de meeste nudes?",
  "Wie heeft de minste bijdrage bij een vakantie voorbereiding?",
  "Wie zou het eerst een alcoholische versnapering weigeren op vakantie?",
  "Wie is het meest stiff in de club?",
  "Wie gebruikt de wc-borstel niet?",
  "Wie trouwt het snelst een drugsbaron?",
  "Wie gaat het snelst scheiden na het huwelijk?",
  "Wie heeft het meest waarschijnlijk seks met {speler}?",
  "Wie zou de beste wingman zijn?",
  "Wie zou de slechtste wingman zijn?",
  "Wie eindigt op een avond uit met een matige 2 in bed?",
  "Wie geeft het snelst hoofd voor 5 euro?",
  "Wie heeft de meeste green flags?",
  "Wie is het goorst op een avond uit?",
  "Wie heeft de meeste sex appeal?",
  "Wie haalt de meeste rondjes?",
  "Wie haalt de minste rondjes?",
];
